# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
target ‘吉林科技馆’ do
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
# Pods for 吉林科技馆
 pod 'FMDB'
 pod 'Masonry'
 pod 'MJExtension'
 pod 'MJRefresh'
# use_frameworks!
# pod 'ReactiveCocoa'
end
